server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotels
    username: postgres
    password: miBD

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
